name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  # repo:
  #   descripton: 'Repo to query (e.g. jon-bell/jqf), defaults to the current'
  #   required: false
  # head_sha:
  #   description: 'SHA to create check run for, defaults to the head sha triggering this action'
  #   required: false
  # workflow_id:
  #   description: 'Workflow ID to query, defaults to the workflow triggering this action'
  #   required: false
  # include_branches:  
  #   description: 'Names of branches to include in the query'
  #   required: true
  #   default: 'main'
  sha_to_post_site_to:
    description: 'Where the check run goes'
    required: false
  benchmarks:
    description: 'Benchmark targets to include in the report'
    required: false
    default: 'ant,bcel,closure,maven,rhino'
  comparisons:
    description: 'Branch info from the jon-bell/list-workflow-runs-by-branch action'
    required: true
  GITHUB_TOKEN:
    required: true
    description: 'Pass the GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'dist/index.js'
