name: 'fuzzing-build-site-action'
description: 'Generate HTML + MD reports for a fuzzing campaign, including comparison branches if available'
author: 'Jonathan Bell'
inputs:
  sha_to_post_site_to:
    description: 'Where the check run goes'
    required: false
  benchmarks:
    description: 'Benchmark targets to include in the report'
    required: false
    default: 'ant,bcel,closure,maven,rhino'
  comparisons:
    description: 'Branch info from the jon-bell/list-workflow-runs-by-branch action'
    required: true
  GITHUB_TOKEN:
    required: true
    description: 'Pass the GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'dist/index.js'
