---
title: "Fuzzer Evaluation - TEMPLATE THAT SHOULD NOT BE RENDERED DIRECTLY EXCEPT FOR DEV"
output: html_document
params:
  benchmark: 'ant'
  artifactURL: "https://ci.in.ripley.cloud/logs"
  dataDirs: '{"dataDirs": [{"path": "/ci-logs/public/jon-bell/JQF/c6e3b2417931d479104f59065da8ea85c7d07f31/Smoke test evaluation - 10 minutes, 5 trials/1604218427/2/artifacts", "name": "dummy-debug-ignore-this"}, {"name": "fast-collision-free-coverage", "path": "/ci-logs/public/jon-bell/JQF/cb70af65d5c0ac1a084c318c2b7260d6710d4ce9/Smoke test evaluation - 10 minutes, 5 trials/1607328380/1/artifacts"}, {"name": "reporting-ci", "path": "/ci-logs/public/jon-bell/JQF/8468ed5f28da5c3d79f85a1a0bcc8d8a8e7ccbd9/Smoke test evaluation - 10 minutes, 5 trials/1604384300/1/artifacts"}]}'
  baseDir: "/ci-logs/"
---

```{r st1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(purrr)
library(tibble)
library(readr)
library(dplyr)
library(stringr)
library(ggplot2)
library(knitr)
library(rjson)
library(kableExtra)
```

# %TARGET%
```{r %TARGET%-setup, include=FALSE}
linkToArtifactFile <- function(pathToFile, fileName, linkName){
        paste0("[",linkName,"](",ARTIFACTS_BASE_URL, substring(pathToFile,nchar(params$baseDir)),"/",fileName,")")
}
readResultFile <- function(file, config) {
  read_csv(file, col_types=cols(.default="d")) %>%
          add_column(filename = file, config=config) %>%
          extract(filename, into = c("path","filename"), regex = "(.*)/([^/]*_plot_data.*)") %>%
          extract(filename, into = c("index"),".*_plot_data_(\\d+)",remove=FALSE)%>%
          mutate(
                  campaignSecs = `# unix_time` - min(`# unix_time`))
}


readExperimentResults <- function(dataDir) {
  dat <- list.files(path=dataDir$path, recursive = F,
             pattern=paste0(localParams$benchmark,"_plot_data_*"),
             full.names = TRUE) %>%
        map_df(~readResultFile(.,dataDir$name)) %>%
        mutate(campaignMins = floor(campaignSecs / 60)) %>%
        complete(config, filename, campaignMins) %>%
        fill(names(.)) %>%
        group_by(campaignMins, config, path, filename, index) %>%
        summarise(across(everything(), last))  %>%
        mutate(total_inputs=invalid_inputs+valid_inputs)
   if(!("b1" %in% colnames(dat))){
           dat <- dat %>% mutate(b0 = NA, b1 = NA, b2 = NA)
   }
   if("all_covered_probes" %in% colnames(dat)){
           dat %>% mutate(cov = all_covered_probes)
   }
   else if("all_cov" %in% colnames(dat)){
           dat %>% mutate(cov=all_cov)
   }
   else {
           dat %>% mutate(cov = NA)
   }
}

# Load plot_data
configs <- fromJSON(params$dataDirs)$dataDirs
data <- map_dfr(configs, readExperimentResults)
byFile <- data %>%
        group_by(config, filename, index)

summary <- byFile %>%
        group_by(campaignMins, config) %>%
        summarise(across(everything(), list(avg=mean,max = max,min = min))) 

# Load JaCoCo branch data
readJaCoCo <- function(dataDir){
  jsonFile <- paste0(dataDir$path,"/",params$benchmark,"_jacoco_summary.json")
  if(file.exists(jsonFile)){
    as.data.frame(fromJSON(file=jsonFile)) %>% add_column(config=dataDir$name)
  } else{
    data.frame(config=c(dataDir$name),branchesCovered=c(NA),branchesTotal=c(NA))
  }
}


jacoco <- map_dfr(configs, readJaCoCo)
hasB1 <- any(which(!is.na(byFile$b1)))
hasB2 <- any(which(!is.na(byFile$b2)))
```

## Branch Probes Over Time

```{r %TARGET%-fig-branches-over-time, echo = FALSE}
ggplot(
        data = summary,
        aes(x = campaignMins, y = cov_avg, group = config, color = config)
) +
        geom_ribbon(aes(ymin = cov_min, ymax = cov_max, group = config, fill = config),
                    linetype = 0, alpha = 0.3) +
        geom_line(size = 0.35) +
        theme_linedraw() +
        xlab("Campaign Time (minutes)") +
        ylab("Branch Probes Covered") +
        theme(text = element_text(size = 6), axis.line = element_line(colour = "black", size = 0.01)) 
ggsave("%TARGET%-branches-over-time.pdf", device="pdf")
```

[Download this graph as PDF](%SITE_BASE_URL%%TARGET%-branches-over-time.pdf)

```{r %TARGET%-b1-head, eval=hasB1, echo = FALSE}
knitr::asis_output("### B(1) Over Time") 
```

```{r %TARGET%-b1, eval=hasB1, echo = FALSE}
ggplot(
        data = summary,
        aes(x = campaignMins, y = b1_avg, group = config, color = config)
) +
        geom_ribbon(aes(ymin = b1_min, ymax = b1_max, group = config, fill = config),
                    linetype = 0, alpha = 0.3) +
        geom_line(size = 0.35) +
        theme_linedraw() +
        xlab("Campaign Time (minutes)") +
        ylab("B(1)") +
        theme(text = element_text(size = 6), axis.line = element_line(colour = "black", size = 0.01)) 
ggsave("%TARGET%-b1-over-time.pdf", device="pdf")
```

```{r %TARGET%-b1-link, eval=hasB1, echo = FALSE}
knitr::asis_output("[Download this graph as PDF](%SITE_BASE_URL%%TARGET%-b1-over-time.pdf)") 
```

```{r %TARGET%-b2-head, eval=hasB2, echo = FALSE}
knitr::asis_output("### B(2) Over Time") 
```

```{r %TARGET%-b2-link, eval=hasB2, echo = FALSE}
ggplot(
        data = summary,
        aes(x = campaignMins, y = b2_avg, group = config, color = config)
) +
        geom_ribbon(aes(ymin = b2_min, ymax = b2_max, group = config, fill = config),
                    linetype = 0, alpha = 0.3) +
        geom_line(size = 0.35) +
        theme_linedraw() +
        xlab("Campaign Time (minutes)") +
        ylab("B(2)") +
        theme(text = element_text(size = 6), axis.line = element_line(colour = "black", size = 0.01)) 
ggsave("%TARGET%-b2-over-time.pdf", device="pdf")
```

```{r %TARGET%-b2, eval=hasB2, echo = FALSE}
knitr::asis_output("[Download this graph as PDF](%SITE_BASE_URL%%TARGET%-b2-over-time.pdf)") 
```

### Final branch coverage by fuzzing config
```{r %TARGET%-table-branches-by-config, echo = FALSE, message = FALSE, results='asis'}
summaryCoverageTable <- byFile %>%
        group_by(filename, path, config) %>%
                summarise(probesHit = max(cov), `B(1)` = max(b1), `B(2)` = max(b2)) %>%
                group_by(config, path) %>%
                        summarise(Average.probesHit = mean(probesHit), SD.probesHit = sd(probesHit),
                                `Average.B(1)` = mean(`B(1)`), `SD.B(1)` = sd(`B(1)`),
                                `Average.B(2)` = mean(`B(2)`), `SD.B(2)` = sd(`B(2)`)) %>%
                ungroup() %>%
        left_join(jacoco,by="config") %>%
        mutate(
                config=linkToArtifactFile(path, paste0("jacoco-",params$benchmark,"/"), config)
                ) %>%
        rename(Configuration=config, JaCoCo.Br.Cov=branchesCovered,JaCoCo.Br.Tot=branchesTotal)  %>%
        relocate(JaCoCo.Br.Cov,.before=JaCoCo.Br.Tot) %>% select(-path) %>% select_if(~ !all(is.na(.)))
kable(summaryCoverageTable, format="simple", booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                        scientific = FALSE)) 
```

### Final branch coverage by fuzzing run
```{r %TARGET%-table-branches-by-run, echo = FALSE,  results='asis'}
branchCovByFuzzingRun <- byFile %>%
        group_by(config, path, filename) %>%
        summarise(`Probes Hit` = max(cov), `B(1)` = max(b1), `B(2)` = max(b2)) %>%
        mutate(filename=linkToArtifactFile(path, filename, filename)) %>% ungroup() %>% select(-path)  %>% select_if(~ !all(is.na(.)))

kable(branchCovByFuzzingRun, format="simple", booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                         scientific = FALSE))
```


## Inputs Over Time
```{r %TARGET%-fig-inputs-over-time, echo = FALSE}

ggplot(
        data = summary,
        aes(x = campaignMins, y = total_inputs_avg, group = config, color = config)
) +
        geom_ribbon(aes(ymin = total_inputs_min, ymax = total_inputs_max, group = config, fill = config), linetype = 0, alpha = 0.3) +
        geom_line(size = 0.35) +
        theme_linedraw() +
        xlab("Campaign Time (minutes)") +
        ylab("Inputs Executed") +
        theme(text = element_text(size = 6), axis.line = element_line(colour = "black", size = 0.01))
        ggsave("%TARGET%-inputs-over-time.pdf", device="pdf")
```

[Download this graph as PDF](%SITE_BASE_URL%%TARGET%-inputs-over-time.pdf)


### Final count of inputs executed by fuzzing config
```{r %TARGET%-table-inputs-by-config, echo = FALSE, message = FALSE,  results='asis'}
inputsByFile <- byFile %>%
        group_by(config, path, filename) %>%
        summarise(invalid_inputs = max(invalid_inputs),
                  valid_inputs = max(valid_inputs),
                  total_inputs = max(invalid_inputs) + max(valid_inputs)) %>%
        mutate(filename=linkToArtifactFile(path, filename, filename)) %>% ungroup() %>% select(-path)

summaryInputsTable <- inputsByFile %>% group_by(config) %>% summarise(
        avg.invalid_inputs = mean(invalid_inputs), sd.invalid_inputs = sd(invalid_inputs),
        avg.valid_inputs = mean(valid_inputs), sd.valid_inputs = sd(valid_inputs),
        avg.total_inputs = mean(total_inputs), sd.total_inputs = sd(total_inputs))

kable(summaryInputsTable, format="simple", booktabs=TRUE, digits=0, format.args = list(big.mark = ",",
                                                                      scientific = FALSE)) 
```

### Final count of inputs executed by fuzzing run
```{r %TARGET%-table-inputs-by-run, echo = FALSE,  results='asis'}
kable(inputsByFile, format="simple",
booktabs=TRUE, digits=0, format.args = list(big.mark = ",", scientific = FALSE))
```

### Failures by fuzzing run

(Not de-duped in any way... failure matching and analysis TBD)
```{r %TARGET%-table-failures-by-run, echo = FALSE, resutls='asis'}
failuresByFile <- byFile %>%
        group_by(config, path, filename) %>%
        summarise(unique_crashes = max(unique_crashes)) %>%
        mutate(
                FailuresTGZ=paste0(str_replace(filename,"_plot_data","_failures"),".tgz"),
                CorpusTGZ=paste0(str_replace(filename,"_plot_data","_corpus"),".tgz"),
                FailuresTGZ=linkToArtifactFile(path, FailuresTGZ, FailuresTGZ),
                CorpusTGZ=linkToArtifactFile(path, CorpusTGZ, CorpusTGZ)
                ) %>% ungroup() %>% select(-path) %>% select(-filename) %>% relocate(FailuresTGZ, .before = unique_crashes) %>% relocate(CorpusTGZ, .before = unique_crashes)
kable(failuresByFile, format="simple",
booktabs=TRUE, digits=0, format.args = list(big.mark = ",", scientific = FALSE))

```