name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: self-hosted
    env:
      RENV_PATHS_ROOT: /ci-logs/renv
    steps:
      - uses: actions/checkout@v2
      - name: Fetch workflow runs to compare to
        id: fetch-compare
        uses: jon-bell/list-workflow-runs-by-branch-action@main
        with:
          include_branches: 'fast-collision-free-coverage, reporting-ci' # will also always try to include the most recent for the branch that triggers the build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: 'eval-3h-5x.yml' #for dev only
          repo: jon-bell/JQF #for dev only
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comparisons: ${{ steps.fetch-compare.outputs.workflow_runs }} 
          milliseconds: 1000
